Add addFriend endpoint
snahornyi/social-network pull request #101
Opened 2021-04-04 21:41 UTC by olegLevochkin

2021-04-04 21:54 UTC, Vlad6501 approved these changes

2021-04-04 22:21 UTC, snahornyi requested changes

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/model/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
Maybe Lazy

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/model/dto/UserDto.java
> +    String friend;
friendName

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/resource/UserResource.java
> +        final String username = authentication.getName();
Move to service layer

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +        if (Objects.isNull(userRepository.findByUsername(username))) {
make it simpler with user==null

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +    public void validateUserFriend(String username) {
validateFriendToAdd

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/model/dto/UserDto.java
> +    String friend;
User can be returned with multiple friends

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/resource/UserResource.java
> +    public ResponseEntity<UserDto> addUserFriends(@RequestBody UserDto userDto) {
As discussed we need just friend username

2021-04-04 22:21 UTC, snahornyi commented on src/main/java/com/kpi/project/service/UserService.java
> +        updatedFriends.add(userRepository.findByUsername(friendName));
Two calls of userRepository.findByUsername(friendName)
1) Here
2) Validator

2021-04-04 22:21 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .withMessage("User with username : username, not exists");
"User with username: username, not exists"

2021-04-05 00:23 UTC, snahornyi requested changes

2021-04-05 00:23 UTC, snahornyi commented on src/main/java/com/kpi/project/model/dto/UserDto.java
> +    Set<User> friendNames;
It's whole users, not just names

2021-04-05 00:34 UTC, snahornyi approved these changes

2021-04-05 00:38 UTC, Vlad6501 approved these changes

2021-04-05 00:58 UTC, merged