Add user validation for age
snahornyi/social-network pull request #102
Opened 2021-04-04 21:54 UTC by Vlad6501

2021-04-04 23:04 UTC, snahornyi requested changes

2021-04-04 23:04 UTC, snahornyi commented on src/main/java/com/kpi/project/service/UserService.java
> +        userValidator.validateUser(userDto.getEmail(), userDto.getUsername(), userDto.getAge());
too many args, pass userDto

2021-04-04 23:04 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +            throw new ValidatorException("insufficient age");
Need better error massage

2021-04-04 23:04 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .isThrownBy(() -> testingInstance.validateUser("", "username", LocalDate.of(2000, 1, 1)))
just pass null

2021-04-04 23:04 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .isThrownBy(() -> testingInstance.validateUser("email@mail.com", "", LocalDate.of(2000, 1, 1)))
pass null

2021-04-04 23:04 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .isThrownBy(() -> testingInstance.validateUser("email@mail.com", "username", LocalDate.of(2000, 1, 1)))
with updates about userDto, than use just givenUser

2021-04-04 23:04 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +
redundant

2021-04-05 00:20 UTC, snahornyi requested changes

2021-04-05 00:20 UTC, snahornyi commented on src/main/java/com/kpi/project/model/dto/UserDto.java
> +    LocalDate age;
u use date params for date of birth, please change variable name

2021-04-05 00:20 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .build();
Do we really need this field, or we can just create simple users

2021-04-05 00:22 UTC, olegLevochkin requested changes

2021-04-05 00:22 UTC, olegLevochkin commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserAgeShouldThrowExceptionIfUserAgeIsUnderSixteen() {
Add test if date is good

2021-04-05 15:43 UTC, snahornyi requested changes
Add test with all correct user args

2021-04-05 15:43 UTC, snahornyi commented on src/main/java/com/kpi/project/model/User.java
> +    @Column(name = "DAYOFBIRTH", nullable = false)
DATE_OF_BIRTH

2021-04-05 15:43 UTC, snahornyi commented on src/main/java/com/kpi/project/model/User.java
> +    LocalDate dayOfBirth;
Rename with updates from previous comment

2021-04-05 15:43 UTC, snahornyi commented on src/main/java/com/kpi/project/model/dto/UserDto.java
> +    LocalDate dayOfBirth;
rename

2021-04-05 15:43 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +            throw new ValidatorException("User must be over sixteen years old");
Change error message

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .dayOfBirth(LocalDate.of(2010, 1, 1))
Do we really need all this data?

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .dayOfBirth(LocalDate.of(2010, 1, 1))
same

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .dayOfBirth(LocalDate.of(2010, 1, 1))
same

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        final UserDto userDto = UserDto.builder()
givenUserDto

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        final UserDto userDto = UserDto.builder()
given UserDto

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .dayOfBirth(LocalDate.of(2010, 1, 1))
redundant data

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserAgeShouldThrowExceptionIfUserAgeIsOverSixteen() {
rename

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        //expected
\n

2021-04-05 15:43 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        final UserDto userDto = UserDto.builder()
givenUserDto

2021-04-05 16:49 UTC, snahornyi requested changes

2021-04-05 16:49 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +            throw new ValidatorException("To register, the user must be over sixteen years old");
Age restriction of sixteen years

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email(null)
default is null already

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .username(null)
same

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .username("user")
username

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        //expected
\n

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        //expected
\n

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserAgeShouldThrowExceptionIfUserAgeIsOlderSixteen() {
rename

2021-04-05 16:49 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserAgeShouldThrowExceptionIfUserAgeIsOlderSixteen() {
refactor this test

2021-04-05 17:59 UTC, snahornyi requested changes

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +        final UserDto givenUserDto = UserDto.builder()
One line

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
Replace with better words

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .email("same@same.com")
same

2021-04-05 17:59 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +                .username("userName")
username

2021-04-05 18:05 UTC, snahornyi requested changes

2021-04-05 18:05 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserAgeShouldUserAgeIsOlderSixteen() {
rename

2021-04-05 18:09 UTC, snahornyi requested changes

2021-04-05 18:09 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void userAgeShouldBeOverSixteen() {
rename

2021-04-05 18:22 UTC, snahornyi requested changes

2021-04-05 18:22 UTC, snahornyi commented on src/test/java/com/kpi/project/validator/UserValidatorTest.java
> +    public void validateUserShouldNotThrowExceptionIfUserAgeOverSixteen() {
rename

2021-04-05 18:28 UTC, snahornyi approved these changes

2021-04-05 18:29 UTC, olegLevochkin approved these changes

2021-04-05 18:31 UTC, merged