Add email validator
snahornyi/social-network pull request #108
Opened 2021-04-05 20:28 UTC by Vlad6501

2021-04-05 20:30 UTC, snahornyi requested changes

2021-04-05 20:30 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +    private final EmailValidator emailValidator = EmailValidator.getInstance();
replace

2021-04-05 20:30 UTC, snahornyi commented on src/main/java/com/kpi/project/validate/UserValidator.java
> +        if (!emailValidator.isValid(userDto.getEmail())) {
Not valid email

2021-04-05 21:06 UTC, olegLevochkin requested changes

2021-04-05 21:06 UTC, olegLevochkin commented on pom.xml
> +            <version>1.4.0</version>
create variable

2021-04-05 21:13 UTC, olegLevochkin approved these changes

2021-04-08 10:18 UTC, snahornyi approved these changes

2021-04-08 10:18 UTC, merged